# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all
Project.destroy_all
Contribution.destroy_all
Genre.destroy_all


# Do this for all models - id #'s won't be in order -
# need to find user through index in array and get id from that user
users = User.create([{username: 'demo', password_digest: BCrypt::Password.create('password')}, {username: 'user1', password_digest: BCrypt::Password.create('password1')}, {username: 'user2', password_digest: BCrypt::Password.create('password2')}, {username: 'user3', password_digest: BCrypt::Password.create('password3')}, {username: 'user4', password_digest: BCrypt::Password.create('password4')}, {username: 'user5', password_digest: BCrypt::Password.create('password5')}])

genres = Genre.create([
  {name: 'folk', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_370,w_370,x_53/v1445382726/genres/folk.jpg'},
  {name: 'rap', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_383,w_383,x_80/v1445382734/genres/rap.jpg'},
  {name: 'pop', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_536,w_536/v1445388511/genres/pop.jpg'},
  {name: 'rock', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_324,w_324/v1445387073/genres/rock.jpg'},
  {name: 'alternative', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_380,w_380/v1445385720/genres/indie_rock.jpg'},
  {name: 'classical', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_1272,w_1272/v1445382736/genres/classical.jpg'},
  {name: 'country', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_313,w_313/v1445817865/genres/country.jpg'},
  {name: 'electronic', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_325,w_325/v1445818179/genres/electronic.jpg'},
  {name: 'jazz', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_319,w_319/v1445818333/genres/jazz.jpg'}
  ])

projects = Project.create([
  {title: "Help Bon Iver Record Our Debut Album", description:"My name is Justin Vernon, and I would like to begin work on my debut album. I'll be recording the album out of a cabin with a very basic recording set-up, and I will do all of the production. My music will be inspired by the Wisconsin winter and my recent breakups with my girlfriend and my last band, DeYarmond Edison.", user_id: users[0].id, genre_id: genres[0].id, deadline: Date.new(2007,2,5), artist_name: 'Bon Iver', funding_goal: 8067.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445832837/for_emma_forever_ago_qffyls.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445832943/03_Skinny_Love_xxjpsu.mp3"},
  {title: 'New Secret Project', description: "Hey everybody! It's Beyonce, and I'm working on a new secret project that will blow your mind. If you look forward to see what I'm up to, please pitch in a few bucks! The resulting project will be coming your way in December, 2013.", user_id: users[1].id, genre_id: genres[2].id, deadline: Date.new(2013,11,3), artist_name: 'Beyonce', funding_goal: 678000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445402103/genres/Project%20Images/Beyonc%C3%A9.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445402213/Project%20Music%20Clips/03_Drunk_in_Love_feat._Jay_Z.mp3"},
  {title: 'Because the Internet Screenplay at Fox Theater', description: "'Critics love to throw around words like “original” and “innovative” all the time. In fact, I’ve heard movie reviewers use both of those words to describe Peter Jackson’s new Hobbit film, The Desolation of Smaug. The strange part is that the movie is actually based on a book, AND is the fifth film in a hugely successful movie franchise, so I don’t really see why “original” is the best word to describe the fantasy epic. We should leave those words to describe something that is truly something different, something unlike everything else out there. The reason I’m saying all this is to heighten the impact of the following statement: Childish Gambino’s Because The Internet is an original work unlike anything I’ve ever experienced.' - JASPER PIKE", user_id: users[1].id, genre_id: genres[1].id, deadline: Date.new(2016,9,18), artist_name: 'Childish Gambino', funding_goal: 54036.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445403341/childish_gambino_haj1wq.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445403092/Project%20Music%20Clips/07_III._Telegraph_Ave.__Oakland__By_Lloyd.m4a"},
  {title: 'Aurora Borealis Tour in Northern Wisconsin', description:"Hey Pickstarter! Justin Vernon here. Your favorite group to fall asleep to is hoping to tour the far reaches of northern Wisconsin. The tour will start at The Porch ice cream parlor in Birchwood, and end in the deep wilderness of the Nicolet National Forest. Free Leinenkugels will be available at the Buckhorn performance in Exeland.", user_id: users[0].id, genre_id: genres[4].id, deadline: Date.new(2016,12,5), artist_name: 'Bon Iver', funding_goal: 90000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445820235/genres/bon_iver.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445820377/04_Woods_hc6ry5.mp3"},
  {title: "Animal Sanctuaries Tour", description:"Hi Everyone! I'm raising money for a tour of California's animal sanctuaries. All proceeds will go to food and medical care for rescued farm animals! Please help me reach my goal of $300,000, and come see me at a concert near you. If you join me at my performance at PreetiRang Sanctuary in Vacaville, you can meet my sponsored cow and goat - Shiva and Kush! Thanks for your donations!", user_id: users[2].id, genre_id: genres[2].id, deadline: Date.new(2016,5,5), artist_name: 'Ariana Grande', funding_goal: 300000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445820921/ariana_grande_fn5dp6.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445821040/02_Problem_feat._Iggy_Azalea_bypkgi.m4a"},
  {title: "Debut US Tour", description:"Remington Gardens is an up-and-coming electronic pop group from Berkeley, CA, hoping to tour many US cities in the summer of 2016, including: \nMilwaukee, WI Nashville, TN \nAustin, TX \nFort Worth, TX \nOakland, CA \nPlease chip in to get us on the road! Thanks!", user_id: users[1].id, genre_id: genres[7].id, deadline: Date.new(2016,6,1), artist_name: 'Remington Gardens', funding_goal: 5760.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445821454/463610_10151126752786231_1432882563_o_1_dphjfd.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445821514/Cloud_Ire_dyly4l.mp3"},
  {title: "Southern US Tour", description:"Nashville gem Tim Angsten wants to bring his sweet country twang to cowboys and gals around the southern US. Pitch in and join him at one of his stops along the way!", user_id: users[1].id, genre_id: genres[6].id, deadline: Date.new(2016,9,1), artist_name: 'Tim Angsten', funding_goal: 16930.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445821611/lmlzn555c0yv1svq5h0ujw45_130832542652879751_TimPanAlleyProductions_z3vqsn.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445821688/01_Desperation_z1enqp.m4a"},
  {title: "Blackstar", description:"On January 8, 2016, David Bowie plans to release a new, 7-song album called Blackstar. The album was already recorded at the Magic Shop studio in New York with local jazz musicians. The record is \"completely bonkers.\" Fund this project to help us ", user_id: users[1].id, genre_id: genres[3].id, deadline: Date.new(2015, 12, 31), artist_name: 'David Bowie', funding_goal: 74690.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445822925/david_bowie_ugg2w0.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445822981/2-02_Under_Pressure_uptwcn.m4a"},
  {title: "Raising money for next album", description:"According to Pitchfork's review of our debut album: 'Diabetics take heed-- this is some sugary stuff, right here. New Orleans duo Generationals are Ted Joyner and Grant Widmer, two guys seemingly obsessed with the twist 'n' shout of yore, jam-packing their tunes with blasts of late-1960s sunshine pop. \"When They Fight, They Fight\" comes from the band's debut, Con Law, which spins a series of songs that don't stray far from \"Fight\"'s time-capsulated goodness. It comes as kind of a pleasant surprise to hear a band from N.O. sound this bright and enraptured in life's simple joys. But man, does this thing flirt with overdoing it. You'd have to be pretty cold-hearted not to raise some sort of a smile for those fun little bossa nova nods, big horns, and amateurish girl-group harmonies. However, if you don't happen to be spending your Sunday flipping through teeny-bopper magazines and kicking your legs in the air with delight, or watching the credits roll on the latest Zooey Deschanel eye-roller, \"Fight\" can feel just a tad too blithe for its own good.'", user_id: users[4].id, genre_id: genres[4].id, deadline: Date.new(2016, 7, 15), artist_name: 'The Generationals', funding_goal: 42706.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445824819/9726603-large_if7vrz.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445286477/u6xpjkbphxmf1ekkw0x2.mp3"},
  {title: "Help us produce a CD of recordings taken from our live concert of classical arias", description:"For many years now, I've had the honor of presenting some of my favorite pieces within my community.  This year, at First Presbyterian, was the first time that it was able to be professionally recorded, and I'm really excited about being able to capture that moment in a CD to share with family, friends, and fans. \n\nAs a classically trained musician, I selected some of my favorite pieces for this show.  Some of these songs are really special to me, like Puccini's \"E lucevan le stelle\" from Tosca. \n\nI had the pleasure of working with some great students and local musicians, and their performances really shined through.  Annette Hoverman accompanied the classical pieces on piano. \n\nMany people who were either at the concert and want to hear it again, or who weren't able to attend and can't wait to hear it for the first time, have already expressed a lot of interest in getting a CD.", user_id: users[2].id, genre_id: genres[5].id, deadline: Date.new(2016, 11, 1), artist_name: 'Jake Wilder', funding_goal: 1200.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445825536/jake_wilder_uk3v3d.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445825757/14_Variations_Souvenir_de_Paganini_-_Op.P1_No.10_-_in_A_BI_37_tmvtas.mp3"},
  {title: "The Music Van", description:"Quite simply, we want to record a series of unique sessions and amazing moments in the back of our bespoke Renault Estafette van to share with the rest of the world. The performances will be available for everyone to enjoy as they will be played out in our podcasts and shared online in video form. We know it sounds crazy but please do bear with us. \n\nThere's a wealth of truly special and talented unsigned artists across the UK who aren't getting the recognition they deserve; The Music Van will travel to every corner to find these artists and to help share their talent.", user_id: users[3].id, genre_id: genres[0].id, deadline: Date.new(2016,3,20), artist_name: 'The Music Bit', funding_goal: 7618.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445826120/tumblr_n2elygyufW1tucbz9o1_500_niubbh.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445826245/06_Love_of_an_Orchestra_jgnydg.mp3"},
  {title: "New Album: Shadows in the Night", description:"A new album is in the making, and I am looking for help funding production and mastering. The album is called 'Shadows in the Night', and it is scheduled to be released in February, 2015. Please support this project!", user_id: users[4].id, genre_id: genres[0].id, deadline: Date.new(2015,1,1), artist_name: 'Bob Dylan', funding_goal: 18550, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445826648/bob_dylan_o8ofkq.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445826719/01_Tangled_Up_In_Blue_uvk7of.mp3"},
  {title: "New Album!", description:"We are Thao & the Get Down Stay Down", user_id: users[3].id, genre_id: genres[0].id, deadline: Date.new(2016,8,17), artist_name: 'Thao & the Get Down Stay Down', funding_goal: 6422.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445826848/Thao_ssqt8o.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445826893/01_We_the_Common_For_Valerie_Bolden_c8npgm.m4a"},
  {title: "Starting a Music Camp", description:"We are New York Symphony Orchestra, and we are hosting a camp for America's top high school musicians. We would like to provide as many scholarships as possible to our students, and if we reach our $200,000 goal, we will be able to provide free tuition for 40 students across the US. Attached is a piece composed and performed by our students last summer. Thank you for supporting our young musicians!", user_id: users[2].id, genre_id: genres[5].id, deadline: Date.new(2016,4,17), artist_name: 'New York Symphony Orchestra', funding_goal: 200000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445827694/FHM-Orchestra-mk2006-03_orizbg.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445827800/03_Midwest_Fantasia_vbd9wr.mp3"},
  {title: "Producing a New Digital Remaster of John Coltrane's Best Works", description:"We are creating a digitally remastered album of John Coltrane's best pieces.", user_id: users[5].id, genre_id: genres[8].id, deadline: Date.new(2016,4,17), artist_name: 'Atlantic Records', funding_goal: 15980.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445828321/johncoltrane-jazz_eq0kg1.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445828357/06_Lush_Life_xlsklr.m4a"},
  {title: "First Annual Eaux Claires Music Festival", description:"Aaron Dessner of the National and I (Justin Vernon) are bringing to life a music festival in Eau Claire, Wisconsin. There will be many fantastic bands and impressive performances to choose from, including performances by the National, Sufjan Stevens and Bon Iver.", user_id: users[0].id, genre_id: genres[4].id, deadline: Date.new(2016,6,5), artist_name: 'Bon Iver', funding_goal: 175000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445829213/eaux-claires-2016_ehak2d.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445820377/04_Woods_hc6ry5.mp3"},

  ])

contributions = Contribution.create([
  {user_id: users[0].id, project_id: projects[12].id, amount: 88920},
  {user_id: users[0].id, project_id: projects[14].id, amount: 24608},
  {user_id: users[0].id, project_id: projects[5].id, amount: 11894},
  {user_id: users[0].id, project_id: projects[2].id, amount: 42080},
  {user_id: users[0].id, project_id: projects[7].id, amount: 824},
  {user_id: users[1].id, project_id: projects[0].id, amount: 98547},
  {user_id: users[1].id, project_id: projects[1].id, amount: 845478},
  {user_id: users[1].id, project_id: projects[3].id, amount: 285070},
  {user_id: users[1].id, project_id: projects[6].id, amount: 12},
  {user_id: users[2].id, project_id: projects[0].id, amount: 203778},
  {user_id: users[2].id, project_id: projects[4].id, amount: 780},
  {user_id: users[2].id, project_id: projects[6].id, amount: 8570},
  {user_id: users[3].id, project_id: projects[6].id, amount: 700},
  {user_id: users[4].id, project_id: projects[0].id, amount: 203778},
  {user_id: users[5].id, project_id: projects[0].id, amount: 15},
  {user_id: users[5].id, project_id: projects[11].id, amount: 30},
  {user_id: users[5].id, project_id: projects[3].id, amount: 900}
  ])
