# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all
Project.destroy_all
Contribution.destroy_all
Genre.destroy_all


# Do this for all models - id #'s won't be in order -
# need to find user through index in array and get id from that user
users = User.create([{username: 'Justin Vernon', password_digest: BCrypt::Password.create('password')}, {username: 'user1', password_digest: BCrypt::Password.create('password1')}, {username: 'user2', password_digest: BCrypt::Password.create('password2')}, {username: 'user3', password_digest: BCrypt::Password.create('password3')}, {username: 'user4', password_digest: BCrypt::Password.create('password4')}, {username: 'user5', password_digest: BCrypt::Password.create('password5')}])

genres = Genre.create([
  {name: 'folk', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_370,w_370,x_53/v1445382726/genres/folk.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_500,w_1500/v1445918375/genres/white-flowers.jpg'},
  {name: 'rap', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_383,w_383,x_80/v1445382734/genres/rap.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_500,w_1500,y_261/v1445918717/genres/concert-crowd-wallpaper-1080p-HD.jpg'},
  {name: 'pop', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_536,w_536/v1445388511/genres/pop.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_333,w_1000/v1445918468/genres/confetti_concert.jpg'},
  {name: 'rock', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_324,w_324/v1445387073/genres/rock.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_841,w_2560/v1445919137/Musical-Instrument-Wallpapers-27_cofboq.jpg'},
  {name: 'alternative', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_380,w_380/v1445385720/genres/indie_rock.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_320,w_960,y_125/v1445923080/Singapore_image_1_m1c64s.jpg'},
  {name: 'classical', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_1272,w_1272/v1445382736/genres/classical.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_496,w_1920/v1445382736/genres/classical.jpg'},
  {name: 'country', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_300,w_300,x_216/v1445917174/country_wzk5y5.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_500,w_1500/v1445921434/0d_oaxska.jpg'},
  {name: 'electronic', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_325,w_325/v1445818179/genres/electronic.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_500,w_1500/v1445922373/Electronic_Music_Dj_Party.jpg_bstacs.jpg'},
  {name: 'jazz', image_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_319,w_319/v1445818333/genres/jazz.jpg', banner_url: 'http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_500,w_1500/v1445922639/jazz_banner_iv65nd.jpg'}
  ])

projects = Project.create([
  {title: "Help Bon Iver Record Our Debut Album", description:"My name is Justin Vernon, and I would like to begin work on my debut album. I'll be recording the album out of a cabin with a very basic recording set-up, and I will do all of the production. My music will be inspired by the Wisconsin winter and my recent breakups with my girlfriend and my last band, DeYarmond Edison.", user_id: users[0].id, genre_id: genres[0].id, deadline: Date.new(2007,2,5), artist_name: 'Bon Iver', funding_goal: 8067.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445832837/for_emma_forever_ago_qffyls.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445832943/03_Skinny_Love_xxjpsu.mp3"},
  {title: 'New Secret Project', description: "Hey everybody! It's Beyonce, and I'm working on a new secret project that will blow your mind. If you look forward to see what I'm up to, please pitch in a few bucks! The resulting project will be coming your way in December, 2013.", user_id: users[1].id, genre_id: genres[2].id, deadline: Date.new(2013,11,3), artist_name: 'Beyonce', funding_goal: 678000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445402103/genres/Project%20Images/Beyonc%C3%A9.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445402213/Project%20Music%20Clips/03_Drunk_in_Love_feat._Jay_Z.mp3"},
  {title: 'Because the Internet Screenplay at Fox Theater', description: "'Critics love to throw around words like “original” and “innovative” all the time. In fact, I’ve heard movie reviewers use both of those words to describe Peter Jackson’s new Hobbit film, The Desolation of Smaug. The strange part is that the movie is actually based on a book, AND is the fifth film in a hugely successful movie franchise, so I don’t really see why “original” is the best word to describe the fantasy epic. We should leave those words to describe something that is truly something different, something unlike everything else out there. The reason I’m saying all this is to heighten the impact of the following statement: Childish Gambino’s Because The Internet is an original work unlike anything I’ve ever experienced.' - JASPER PIKE", user_id: users[1].id, genre_id: genres[1].id, deadline: Date.new(2016,9,18), artist_name: 'Childish Gambino', funding_goal: 54036.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445403341/childish_gambino_haj1wq.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445403092/Project%20Music%20Clips/07_III._Telegraph_Ave.__Oakland__By_Lloyd.m4a"},
  {title: 'Aurora Borealis Tour in Northern Wisconsin', description:"Hey Pickstarter! Justin Vernon here. Your favorite group to fall asleep to is hoping to tour the far reaches of northern Wisconsin. The tour will start at The Porch ice cream parlor in Birchwood, and end in the deep wilderness of the Nicolet National Forest. Free Leinenkugels will be available at the Buckhorn performance in Exeland.", user_id: users[0].id, genre_id: genres[4].id, deadline: Date.new(2016,12,5), artist_name: 'Bon Iver', funding_goal: 90000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445820235/genres/bon_iver.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445820377/04_Woods_hc6ry5.mp3"},
  {title: "Animal Sanctuaries Tour", description:"Hi Everyone! I'm raising money for a tour of California's animal sanctuaries. All proceeds will go to food and medical care for rescued farm animals! Please help me reach my goal of $300,000, and come see me at a concert near you. If you join me at my performance at PreetiRang Sanctuary in Vacaville, you can meet my sponsored cow and goat - Shiva and Kush! Thanks for your donations!", user_id: users[2].id, genre_id: genres[2].id, deadline: Date.new(2016,5,5), artist_name: 'Ariana Grande', funding_goal: 300000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445820921/ariana_grande_fn5dp6.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445821040/02_Problem_feat._Iggy_Azalea_bypkgi.m4a"},
  {title: "Debut US Tour", description:"Remington Gardens is an up-and-coming electronic pop group from Berkeley, CA, hoping to tour many US cities in the summer of 2016, including: \nMilwaukee, WI Nashville, TN \nAustin, TX \nFort Worth, TX \nOakland, CA \nPlease chip in to get us on the road! Thanks!", user_id: users[1].id, genre_id: genres[7].id, deadline: Date.new(2016,6,1), artist_name: 'Remington Gardens', funding_goal: 5760.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445821454/463610_10151126752786231_1432882563_o_1_dphjfd.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445821514/Cloud_Ire_dyly4l.mp3"},
  {title: "Southern US Tour", description:"Nashville gem Tim Angsten wants to bring his sweet country twang to cowboys and gals around the southern US. Pitch in and join him at one of his stops along the way!", user_id: users[1].id, genre_id: genres[6].id, deadline: Date.new(2016,9,1), artist_name: 'Tim Angsten', funding_goal: 16930.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445821611/lmlzn555c0yv1svq5h0ujw45_130832542652879751_TimPanAlleyProductions_z3vqsn.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445821688/01_Desperation_z1enqp.m4a"},
  {title: "Blackstar", description:"On January 8, 2016, David Bowie plans to release a new, 7-song album called Blackstar. The album was already recorded at the Magic Shop studio in New York with local jazz musicians. The record is \"completely bonkers.\" Fund this project to help us ", user_id: users[1].id, genre_id: genres[3].id, deadline: Date.new(2015, 12, 31), artist_name: 'David Bowie', funding_goal: 74690.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445822925/david_bowie_ugg2w0.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445822981/2-02_Under_Pressure_uptwcn.m4a"},
  {title: "Raising money for next album", description:"According to Pitchfork's review of our debut album: 'Diabetics take heed-- this is some sugary stuff, right here. New Orleans duo Generationals are Ted Joyner and Grant Widmer, two guys seemingly obsessed with the twist 'n' shout of yore, jam-packing their tunes with blasts of late-1960s sunshine pop. \"When They Fight, They Fight\" comes from the band's debut, Con Law, which spins a series of songs that don't stray far from \"Fight\"'s time-capsulated goodness. It comes as kind of a pleasant surprise to hear a band from N.O. sound this bright and enraptured in life's simple joys. But man, does this thing flirt with overdoing it. You'd have to be pretty cold-hearted not to raise some sort of a smile for those fun little bossa nova nods, big horns, and amateurish girl-group harmonies. However, if you don't happen to be spending your Sunday flipping through teeny-bopper magazines and kicking your legs in the air with delight, or watching the credits roll on the latest Zooey Deschanel eye-roller, \"Fight\" can feel just a tad too blithe for its own good.'", user_id: users[4].id, genre_id: genres[4].id, deadline: Date.new(2016, 7, 15), artist_name: 'The Generationals', funding_goal: 42706.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445824819/9726603-large_if7vrz.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445286477/u6xpjkbphxmf1ekkw0x2.mp3"},
  {title: "Help us produce a CD of recordings taken from our live concert of classical arias", description:"For many years now, I've had the honor of presenting some of my favorite pieces within my community.  This year, at First Presbyterian, was the first time that it was able to be professionally recorded, and I'm really excited about being able to capture that moment in a CD to share with family, friends, and fans. \n\nAs a classically trained musician, I selected some of my favorite pieces for this show.  Some of these songs are really special to me, like Puccini's \"E lucevan le stelle\" from Tosca. \n\nI had the pleasure of working with some great students and local musicians, and their performances really shined through.  Annette Hoverman accompanied the classical pieces on piano. \n\nMany people who were either at the concert and want to hear it again, or who weren't able to attend and can't wait to hear it for the first time, have already expressed a lot of interest in getting a CD.", user_id: users[2].id, genre_id: genres[5].id, deadline: Date.new(2016, 11, 1), artist_name: 'Jake Wilder', funding_goal: 1200.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445825536/jake_wilder_uk3v3d.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445825757/14_Variations_Souvenir_de_Paganini_-_Op.P1_No.10_-_in_A_BI_37_tmvtas.mp3"},
  {title: "The Music Van", description:"Quite simply, we want to record a series of unique sessions and amazing moments in the back of our bespoke Renault Estafette van to share with the rest of the world. The performances will be available for everyone to enjoy as they will be played out in our podcasts and shared online in video form. We know it sounds crazy but please do bear with us. \n\nThere's a wealth of truly special and talented unsigned artists across the UK who aren't getting the recognition they deserve; The Music Van will travel to every corner to find these artists and to help share their talent.", user_id: users[3].id, genre_id: genres[0].id, deadline: Date.new(2016,3,20), artist_name: 'The Music Bit', funding_goal: 7618.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445826120/tumblr_n2elygyufW1tucbz9o1_500_niubbh.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445826245/06_Love_of_an_Orchestra_jgnydg.mp3"},
  {title: "New Album: Shadows in the Night", description:"A new album is in the making, and I am looking for help funding production and mastering. The album is called 'Shadows in the Night', and it is scheduled to be released in February, 2015. Please support this project!", user_id: users[4].id, genre_id: genres[0].id, deadline: Date.new(2015,1,1), artist_name: 'Bob Dylan', funding_goal: 18550, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445826648/bob_dylan_o8ofkq.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445826719/01_Tangled_Up_In_Blue_uvk7of.mp3"},
  {title: "New Album!", description:"We are Thao & the Get Down Stay Down", user_id: users[3].id, genre_id: genres[0].id, deadline: Date.new(2016,8,17), artist_name: 'Thao & the Get Down Stay Down', funding_goal: 6422.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445826848/Thao_ssqt8o.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445826893/01_We_the_Common_For_Valerie_Bolden_c8npgm.m4a"},
  {title: "Starting a Music Camp", description:"We are New York Symphony Orchestra, and we are hosting a camp for America's top high school musicians. We would like to provide as many scholarships as possible to our students, and if we reach our $200,000 goal, we will be able to provide free tuition for 40 students across the US. Attached is a piece composed and performed by our students last summer. Thank you for supporting our young musicians!", user_id: users[2].id, genre_id: genres[5].id, deadline: Date.new(2016,4,17), artist_name: 'New York Symphony Orchestra', funding_goal: 200000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445827694/FHM-Orchestra-mk2006-03_orizbg.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445827800/03_Midwest_Fantasia_vbd9wr.mp3"},
  {title: "Producing a New Digital Remaster of John Coltrane's Best Works", description:"We are creating a digitally remastered album of John Coltrane's best pieces.", user_id: users[5].id, genre_id: genres[8].id, deadline: Date.new(2016,4,17), artist_name: 'Atlantic Records', funding_goal: 15980.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445828321/johncoltrane-jazz_eq0kg1.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445828357/06_Lush_Life_xlsklr.m4a"},
  {title: "First Annual Eaux Claires Music Festival", description:"Aaron Dessner of the National and I (Justin Vernon) are bringing to life a music festival in Eau Claire, Wisconsin. There will be many fantastic bands and impressive performances to choose from, including performances by the National, Sufjan Stevens and Bon Iver.", user_id: users[0].id, genre_id: genres[4].id, deadline: Date.new(2016,6,5), artist_name: 'Bon Iver', funding_goal: 175000.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445829213/eaux-claires-2016_ehak2d.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445820377/04_Woods_hc6ry5.mp3"},
  {title: "Life Forum (New Album)", description: "For the best young jazz musicians — Clayton is 26 — the music's long history isn't a stumbling block to expression. It's just a reality, a source of connections. It gets complicated, but the sorting-out process happens over time for a working band like Clayton's. It's \"a trio of close friends,\" he told the audience. \"These guys pretty much read my mind.\"", user_id: users[3].id, genre_id: genres[8].id, deadline: Date.new(2016,6,28), artist_name: "Gerald Clayton", funding_goal: 120533.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445915697/MI0003494779.jpg_pfg3qd.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445915836/09_-_Some_Always_bzoexy.mp3"},
  {title: "Digital Lion Tour", description:" Two years ago Blake released a self-titled album of delicate electronic music that was sad and stirring and a great critical success, eventually nominated for the 2011 Mercury prize. About to release a follow-up, Overgrown, Blake might have arrived to meet me full of pushy enthusiasm, standard for an artist on the eve of a launch. Quite the opposite. Erect in his seat in a north London pub, his slim 6ft 5in wrapped in layers of fitted menswear, Blake drinks a coffee and indulges in that great British pleasure.", user_id: users[2].id, genre_id: genres[7].id, deadline: Date.new(2015,10,4), artist_name: "James Blake", funding_goal: 79300.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445917790/4EB8374D81301E8274BE4ADB519F342C_zlq1j5.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445918922/05_Retrograde_fmps97.m4a"},
  {title: "Sadnecessary (New Album)", description:"Kassel, Germany-based bandmates Clemens Rehbein (vocals) and Philipp Dausch (production) pulled together their debut LP, Sadnecessary, over two low-key weeks at home with whatever tools they had laying around — computer, microphone, basic interface — and tossed single \”Stolen Dance\” up on YouTube with the expectation-equivalent of a shrug. Month later: 500,000 views. A little over a year later: more than 56 million views and counting; top-of-charts status in 14 countries; gold, platinum or double-platinum plaques from Austria to Australia; and a calendar that's bouncing them from the Montreaux Jazz Festival to Reading and Leeds. And they'll probably be in the States eventually: Sadnecessary is due for U.S. release in October.", user_id: users[4].id, genre_id: genres[4].id, deadline: Date.new(2016,3,15), artist_name: "Milky Chance", funding_goal: 11405.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445917338/milky-chance_i7x6gy.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445918993/11_Stolen_Dance_mkdbkj.m4a"},
  {title: "Already Free (New Album)", description:"Trucks has appeared twice in Rolling Stone's list of \"The 100 Greatest Guitarists of All Time\". He was listed as 81st in 2003 and 16th in 2011. An article in The Wall Street Journal described him as \"the most awe-inspiring electric slide guitar player performing today\". In 2007, Trucks appeared on the cover of Rolling Stone for an article called the \"New Guitar Gods\".Trucks is reported to be a creative guitarist and according to his uncle, Allman Brothers drummer Butch Trucks, \"He never does the same thing twice\". An article in The Washington Post described Trucks's guitar style as \"notes and chords that soar, slice and glide, sounding like a cross between Duane Allman on a 1961 Gibson Les Paul and John Coltrane on tenor sax\". The Derek Trucks Band's album Already Free debuted at No. 19 on the Billboard Top 200Chart, and No. 1 on the Internet chart, No. 4 on the Rock chart and No. 1 on the Blues chart.", user_id: users[4].id, genre_id: genres[6].id, deadline: Date.new(2015,9,2), artist_name: "Derek Trucks", funding_goal: 992002.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445916903/10679587_10152473795799667_3144983034781829296_o_rpstih.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445917008/02_Something_to_Make_You_Happy_iyw7sm.mp3"},
  {title: "Graceland Tour", description: "Graceland is the seventh studio album by American singer-songwriter Paul Simon. Produced by Simon and Roy Halee, the album released on August 25, 1986 by Warner Bros. Records. In the early 1980s, Simon's career hit a low point. Following a very successful but contentious reunion with former partner Art Garfunkel, Simon's marriage fell apart and his previous record, Hearts and Bones (1983), was a significant commercial disappointment. In 1984, after a period of depression, Simon became fascinated with a bootleg cassette of South African township music. He planned a trip to Johannesburg in the new year with Halee, where he spent two weeks recording with South African musicians. Recorded between 1985–86, Graceland features an eclectic mixture of musical styles, including pop, rock, a cappella, zydeco,isicathamiya, and mbaqanga. Simon created new compositions inspired by the recordings made in Johannesburg, collaborating with both African and American artists. Simon faced controversy for seemingly breaking the cultural boycott imposed by the rest of the world against South Africa because of its policy of apartheid.", user_id: users[5].id, genre_id: genres[3].id, deadline: Date.new(2017,2,1), artist_name: "Paul Simon", funding_goal: 435988.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445916505/800px-Graceland_cover_-_Paul_Simon_muftpt.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445916574/01-02-_Graceland_hydcwg.mp3"},
  {title: "Songs for the Deaf (New Album)", description: "In certain circles, Josh Homme was already plenty famous before Queens of the Stone Age. He was a founding member and guitarist for stoner metal outfit Kyuss – a staple of the Palm Desert scene during the late ’80s and early ’90s and a band’s band that became legendary for combining sludgy guitar rock with spacey jams and elements of thrash.", user_id: users[4].id, genre_id: genres[3].id, deadline: Date.new(2018,1,12), artist_name: "Queens of the Stone Age", funding_goal: 79300.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445921392/munk-one-queens-of-the-stone-age_klclni.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445921808/03_No_One_Knows_lhidhw.m4a"},
  {title: "Kids (New Album)", description:" For every person that loved Ray Tintori’s video for MGMT’s Kids, there were two therapists sending their contact info to the monster-terrorized child’s mom. The little tyke looked terrified! So the old folks at Breakfast At Sulimay’s just filmed a very special video-review segment of their show, applying their usual brand of bran-muffin music crit to this Oracular Spectacular comment-baiting clip. Ann, Bill, and Joe are in agreement on this one. Ann’s face says it all. Joe could \“find no value in it at all,\” but that’s probably because he didn’t realize the mom is played by Joanna Newsom at first, either.", user_id: users[5].id, genre_id: genres[4].id, deadline: Date.new(2017,3,2), artist_name: "MGMT", funding_goal: 470303.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445920741/e2b7cff298220a7f5bececac94eaba0b_com5sv.png", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445921754/04_Electric_Feel_qyeupt.mp3"},
  {title: "The Clone Johann Sebastian Bach Concert", description:"In 2011, Bach’s grave was dug up and DNA was successfully extracted. Scientists contend that, with the right amount of money and nanotechnology, we can have Bach up and running again in less than 23 years. This is why we’re putting together a Pickstarter page to fund Bach’s next concert. We know it’s a long time to wait, but think how retro his music will be by that point! Serious, help out this project. Bach’s clone will really freak when he realizes how much people actually cared about his DNA-equivalent-self’s music of the seventeeth century. We’ll also be holding a thirty-minute Q&A session in the lobby after the show.", user_id: users[3].id, genre_id: genres[5].id, deadline: Date.new(2037,6,1), artist_name: "Johann Sebastian Bach", funding_goal: 1500300.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445920354/1392905500_lpxbdt.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445921586/01_Track_01_q6oeow.m4a"},
  {title: "Kanye West’s Tour Intergalactica", description:"In the musical race for space, we all know who will win. Support Kanye as he brings his sweet sweet song to non-terrestrial life. Money will go toward his spaceship, fuel, Clif bars for the trip, and a really really loud speaker system. Help us send Kanye as far away from earth as possible so he can show the alien lifeforms out there who really is the best. And how on earth did Taylor swift win at the VMAs? Seriously. That would never happen in space. Yet another reason to fund Kanye’s tour in space.", user_id: users[2].id, genre_id: genres[1].id, deadline: Date.new(2018,11,11), artist_name: " Kanye West", funding_goal: 70020010.00, image_url: "http://res.cloudinary.com/daqcetxc6/image/upload/v1445919850/Q_YaVui7_400x400_efgdin.jpg", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445921690/04_Gold_Digger_hvsu2v.m4a"},
  {title: "Party in the USA (Event)", description:"We’re hosting the biggest party in the USA musical event ever. It’s going to be a huge party in the USA somewhere. But first we need tons of money to get Miley Cirus to perform at this party in the USA. If she is able to make it, it will be a party, particularly in the USA. Help us out Pickstarter!", user_id: users[1].id, genre_id: genres[2].id, deadline: Date.new(2016,4,15), artist_name: "Miley Cyrus", funding_goal: 2090300.00, image_url: " http://res.cloudinary.com/daqcetxc6/image/upload/v1445919170/images_m7sidg.jpg ", sound_clip_url: "http://res.cloudinary.com/daqcetxc6/video/upload/v1445921634/01_Party_In_the_U.S.A._eyjfzn.m4a"}
  ])

contributions = Contribution.create([
  {user_id: users[0].id, project_id: projects[12].id, amount: 88920},
  {user_id: users[0].id, project_id: projects[14].id, amount: 24608},
  {user_id: users[0].id, project_id: projects[5].id, amount: 11894},
  {user_id: users[0].id, project_id: projects[2].id, amount: 42080},
  {user_id: users[0].id, project_id: projects[7].id, amount: 824},
  {user_id: users[1].id, project_id: projects[0].id, amount: 98547},
  {user_id: users[1].id, project_id: projects[1].id, amount: 845478},
  {user_id: users[1].id, project_id: projects[3].id, amount: 285070},
  {user_id: users[1].id, project_id: projects[6].id, amount: 12},
  {user_id: users[2].id, project_id: projects[0].id, amount: 203778},
  {user_id: users[2].id, project_id: projects[4].id, amount: 780},
  {user_id: users[2].id, project_id: projects[6].id, amount: 8570},
  {user_id: users[3].id, project_id: projects[6].id, amount: 700},
  {user_id: users[4].id, project_id: projects[0].id, amount: 203778},
  {user_id: users[5].id, project_id: projects[0].id, amount: 15},
  {user_id: users[5].id, project_id: projects[11].id, amount: 30},
  {user_id: users[5].id, project_id: projects[3].id, amount: 900}
  ])
